Add node and ps statistics

diff --git a/3par b/3par
--- a/3par
+++ b/3par
@@ -170,6 +170,147 @@ case $1 in
                 awk -F":" 'FNR == 32 {gsub(" ",""); print $2}' <<< "${OUTPUT}"
                 ;;
 
+	node_state)
+		if [[ -z $2 ]]; then
+			printf '\n%s\n\n' "Node number is required"
+			exit 1
+		fi
+		OUTPUT=$(${CONNECTION} 'shownode -showcols State '${2}'' 2>/dev/null)
+                if [[ $? -ne 0 ]]; then
+                        printf '\n%s\n\n' "Storage array is unavailable"
+                        exit 1
+                fi
+		awk 'FNR == 2 {print $1}' <<< "${OUTPUT}"
+		;;
+
+	node_temp_ambient)
+                if [[ -z $2 ]]; then
+                        printf '\n%s\n\n' "Node number is required"
+                        exit 1
+                fi
+                OUTPUT=$(${CONNECTION} 'shownodeenv -n '${2}'' 2>/dev/null)
+                if [[ $? -ne 0 ]]; then
+                        printf '\n%s\n\n' "Storage array is unavailable"
+                        exit 1
+                fi
+                awk 'FNR == 6 {print $2}' <<< "${OUTPUT}"
+                ;;
+
+	 node_temp_midplane)
+                if [[ -z $2 ]]; then
+                        printf '\n%s\n\n' "Node number is required"
+                        exit 1
+                fi
+                OUTPUT=$(${CONNECTION} 'shownodeenv -n '${2}'' 2>/dev/null)
+                if [[ $? -ne 0 ]]; then
+                        printf '\n%s\n\n' "Storage array is unavailable"
+                        exit 1
+                fi
+                awk 'FNR == 7 {print $2}' <<< "${OUTPUT}"
+                ;;
+
+	ps_state)
+                if [[ -z $2 ]]; then
+                        printf '\n%s\n\n' "Node number is required"
+                        exit 1
+                fi
+		if [[ -z $3 ]]; then
+                        printf '\n%s\n\n' "PS number is required"
+                        exit 1
+                fi
+                OUTPUT=$(${CONNECTION} 'shownode -showcols PS,PSState -ps '${2}'' 2>/dev/null)
+                if [[ $? -ne 0 ]]; then
+                        printf '\n%s\n\n' "Storage array is unavailable"
+                        exit 1
+                fi
+                awk '$1 ~ /'$3'/ {print $2}' <<< "${OUTPUT}"
+                ;;
+
+	ps_ac_state)
+                if [[ -z $2 ]]; then
+                        printf '\n%s\n\n' "Node number is required"
+                        exit 1
+                fi
+                if [[ -z $3 ]]; then
+                        printf '\n%s\n\n' "PS number is required"
+                        exit 1
+                fi
+                OUTPUT=$(${CONNECTION} 'shownode -showcols PS,ACState -ps '${2}'' 2>/dev/null)
+                if [[ $? -ne 0 ]]; then
+                        printf '\n%s\n\n' "Storage array is unavailable"
+                        exit 1
+                fi
+                awk '$1 ~ /'$3'/ {print $2}' <<< "${OUTPUT}"
+                ;;
+
+	ps_dc_state)
+                if [[ -z $2 ]]; then
+                        printf '\n%s\n\n' "Node number is required"
+                        exit 1
+                fi
+                if [[ -z $3 ]]; then
+                        printf '\n%s\n\n' "PS number is required"
+                        exit 1
+                fi
+                OUTPUT=$(${CONNECTION} 'shownode -showcols PS,DCState -ps '${2}'' 2>/dev/null)
+                if [[ $? -ne 0 ]]; then
+                        printf '\n%s\n\n' "Storage array is unavailable"
+                        exit 1
+                fi
+                awk '$1 ~ /'$3'/ {print $2}' <<< "${OUTPUT}"
+                ;;
+
+	ps_bat_state)
+                if [[ -z $2 ]]; then
+                        printf '\n%s\n\n' "Node number is required"
+                        exit 1
+                fi
+                if [[ -z $3 ]]; then
+                        printf '\n%s\n\n' "PS number is required"
+                        exit 1
+                fi
+                OUTPUT=$(${CONNECTION} 'shownode -showcols PS,BatState -ps '${2}'' 2>/dev/null)
+                if [[ $? -ne 0 ]]; then
+                        printf '\n%s\n\n' "Storage array is unavailable"
+                        exit 1
+                fi
+                awk '$1 ~ /'$3'/ {print $2}' <<< "${OUTPUT}"
+                ;;
+
+	ps_fan_state)
+                if [[ -z $2 ]]; then
+                        printf '\n%s\n\n' "Node number is required"
+                        exit 1
+                fi
+                if [[ -z $3 ]]; then
+                        printf '\n%s\n\n' "PS number is required"
+                        exit 1
+                fi
+                OUTPUT=$(${CONNECTION} 'shownode -showcols PS,FanState -ps '${2}'' 2>/dev/null)
+                if [[ $? -ne 0 ]]; then
+                        printf '\n%s\n\n' "Storage array is unavailable"
+                        exit 1
+                fi
+                awk '$1 ~ /'$3'/ {print $2}' <<< "${OUTPUT}"
+                ;;
+
+	ps_charge_level)
+                if [[ -z $2 ]]; then
+                        printf '\n%s\n\n' "Node number is required"
+                        exit 1
+                fi
+                if [[ -z $3 ]]; then
+                        printf '\n%s\n\n' "PS number is required"
+                        exit 1
+                fi
+                OUTPUT=$(${CONNECTION} 'shownode -showcols PS,ChrgLvl -ps '${2}'' 2>/dev/null)
+                if [[ $? -ne 0 ]]; then
+                        printf '\n%s\n\n' "Storage array is unavailable"
+                        exit 1
+                fi
+                awk '$1 ~ /'$3'/ {print $2}' <<< "${OUTPUT}"
+                ;;
+
 	*)
 		printf '\n%s\n\n' "Unrecognized parameter"
 		exit 1
